#pragma once

/** GENERAL **/
#define LOW_SPEED_TASK_FREQ_HZ 100
#define PRECHARGE_VOLTAGE

/** CAN **/
#define NUM_IDS_SENSE 12
#define NUM_IDS_MAIN 2
#define NUM_IDS_INV 12

/** Inverters **/
#define TORQUE_SETPOINT 2
#define POS_TORQUE_LIMIT 3
#define NEG_TORQUE_LIMIT (-3)
#define INV_CAN_TIMEOUT_MS 300

/** Analog **/
#define VOLTAGE_TOL 0.001
#define ADC_MAX_VAL 4095
#define ADC_MAX_VOLTAGE 3.3

/** Accelerator **/
#define ACCEL_A_MAX_V 2.8
#define ACCEL_A_OFFSET_V 0.2
#define ACCEL_A_RANGE_V (ACCEL_A_MAX_V - ACCEL_A_OFFSET_V)
#define ACCEL_A_IRRATIONAL_LOW_V 0.05

#define ACCEL_B_MAX_V 2.8
#define ACCEL_B_OFFSET_V 0.2
#define ACCEL_B_RANGE_V (ACCEL_B_MAX_V - ACCEL_B_OFFSET_V)
#define ACCEL_B_IRRATIONAL_LOW_V 0.05

#define ACCEL_MAX_DISAGREEMENT 10

/** Brakes **/
#define BPS_MAX_V 2.8
#define BPS_MIN_V 0.2
#define BPS_RANGE_V (BPS_MAX_V - BPS_MIN_V)
#define BPS_IRRATIONAL_HIGH_V 3.15
#define BPS_IRRATIONAL_LOW 0.05
#define BPS_MAX_PRESSURE_PSI 5076.32
#define BRAKE_PRESSED_PSI 55
#define BPS_UPDATE_FREQ LOW_SPEED_TASK_FREQ_HZ

/** APPS **/
#define APPS_ACCEL_IRRATIONAL_TIMEOUT_MS 100
#define APPS_ACCEL_DISAGREE_TIMEOUT_MS 100
#define APPS_BPS_IRRATIONAL_TIMEOUT_MS 100
#define APPS_DOUBLE_PEDAL_TIMEOUT_MS 100

#define APPS_UPDATE_FREQ LOW_SPEED_TASK_FREQ_HZ
#define APPS_ACCEL_DOUBLE_PEDAL_THRESHOLD 15