#pragma once

#ifndef VC_TEST
#include <stm32g4xx_hal.h>
#endif

/** GENERAL **/
#define LOW_SPEED_TASK_FREQ_HZ 100
#define MIN_PRECHARGE_VOL 400
#define PRECHARGE_MIN_TIME_MS 2000
#define PRECHARGE_MAX_TIME_MS 5000
#define OVERSPEED_RPM 20000
#define RTD_HOLD_TIME 1000

/** CAN **/
#define CAN_SENSE FDCAN1
#define CAN_MAIN FDCAN2
#define CAN_INV FDCAN3
#define NUM_IDS_MAIN 4
#define NUM_IDS_INV 16

/** CONTROLS **/
#define REGEN_ENABLED 0

#define CS_LAT_FACTOR_ACC 0.2
#define CS_LONG_FACTOR_ACC 0.1
#define CS_LONG_SPLIT_ACC 0.4
#define CS_LAT_FACTOR_BRAKE 0.5
#define CS_LONG_FACTOR_BRAKE 0.1
#define CS_LONG_SPLIT_BRAKE 0.65

#define CS_MIN_ACCEL_PCT 0
#define CS_MAX_ACCEL_PCT 100
#define CS_MIN_BRAKE_PCT 100
#define CS_MAX_BRAKE_PCT 750
#define CS_MIN_STEER_PCT 0
#define CS_MAX_STEER_PCT 100

/** Inverters **/
#define MAX_TORQUE 100
#define POS_TORQUE_LIMIT 100
#define NEG_TORQUE_LIMIT (-4)
#define INV_CAN_TIMEOUT_MS 300
#define INV_LIMIT_TOL 5

/** Analog **/
#define VOLTAGE_TOL 0.001
#define ADC_MAX_VAL 4095
#define ADC_MAX_VOLTAGE 3.3

/** Accelerator **/
#define ACCEL_A_IRRATIONAL_HIGH_ADC 4000
#define ACCEL_A_MAX_ADC 3400
#define ACCEL_A_OFFSET_ADC 600
#define ACCEL_A_RANGE_ADC (ACCEL_A_MAX_ADC - ACCEL_A_OFFSET_ADC)
#define ACCEL_A_IRRATIONAL_LOW_ADC 50

#define ACCEL_B_IRRATIONAL_HIGH_ADC 2500
#define ACCEL_B_MAX_ADC 1800
#define ACCEL_B_OFFSET_ADC 300
#define ACCEL_B_RANGE_ADC (ACCEL_B_MAX_ADC - ACCEL_B_OFFSET_ADC)
#define ACCEL_B_IRRATIONAL_LOW_ADC 50

#define ACCEL_MAX_DISAGREEMENT 10

#define ACCEL_POS_TOL 1

/** Brakes **/
// 0.5 - 4.5v maps to 0 - 3000 psi
#define BPS_F_IRRATIONAL_HIGH_ADC 2000
#define BPS_F_MAX_ADC 1600    // ~ 1100 psi
#define BPS_F_OFFSET_ADC 400     // ~ 0 psi
#define BPS_F_RANGE_ADC (BPS_F_MAX_ADC - BPS_F_OFFSET_ADC)
#define BPS_F_IRRATIONAL_LOW_ADC 200
#define BPS_F_MAX_PSI 1300
#define BPS_F_MIN_PRESSURE_PSI 0

#define BPS_R_IRRATIONAL_HIGH_ADC 2000
#define BPS_R_MAX_ADC 900    // ~ 1100 psi
#define BPS_R_OFFSET_ADC 300     // ~ 0 psi
#define BPS_R_RANGE_ADC (BPS_R_MAX_ADC - BPS_R_OFFSET_ADC)
#define BPS_R_IRRATIONAL_LOW_ADC 200
#define BPS_R_MAX_PSI 1300

#define BPS_PRESSED_PCT 0.1
#define BPS_UPDATE_FREQ LOW_SPEED_TASK_FREQ_HZ
#define BPS_PSI_TOL 1

/** DriverInputs **/
#define DI_ACCEL_IRRATIONAL_TIMEOUT_MS 100
#define DI_ACCEL_DISAGREE_TIMEOUT_MS 100
#define DI_BPS_IRRATIONAL_TIMEOUT_MS 100
#define DI_DOUBLE_PEDAL_TIMEOUT_MS 100

#define STEER_IRRATIONAL_MAX_ADC 4000
#define STEER_MAX_ADC 3500
#define STEER_OFFSET_ADC 2050
#define STEER_RANGE_ADC (STEER_MAX_ADC - STEER_OFFSET_ADC)
#define HALF_STEER_RANGE_ADC (STEER_RANGE_ADC / 2)
#define STEER_IRRATIONAL_MIN_ADC 1000

#define DI_UPDATE_FREQ LOW_SPEED_TASK_FREQ_HZ
#define DI_ACCEL_DOUBLE_PEDAL_THRESHOLD 15

/** VehicleState **/
#define VS_UPDATE_FREQ LOW_SPEED_TASK_FREQ_HZ
